# Generated by Django 5.2.1 on 2025-05-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0002_categorydb_placedb_shopdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdb',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationapp.categorydb'),
        ),
        migrations.AddField(
            model_name='shopdb',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationapp.placedb'),
        ),
    ]
