# Generated by Django 5.2.1 on 2025-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0003_shopdb_category_name_shopdb_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdb',
            name='shopimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
