# Generated by Django 4.2.6 on 2025-06-01 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0004_shopdb_shopimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_visited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('purpose', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationapp.categorydb')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationapp.placedb')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationapp.shopdb')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
